- name: List sites to be added
  find:
    paths: "{{ wh_root }}/sites"
    file_type: directory
  register: sites
  tags: never  # task moved to main.yml
  when: False

- debug: var=sites.files
- debug: msg="{{ sites.files | map(attribute='path') |list }}"

- name: Add each site
  include_tasks: add-site.yml
  vars:
    vhost: "{{ item | basename }}"
  with_items: "{{ sites.files | map(attribute='path') |list }}"


