- name: Generate WP DB password
  set_fact:
    vhost_db_pass: >-
      "{{ lookup('password',
      'credentials/' + ansible_host +'/'+ vhost +'/db_pass length=16') }}"

- name: Find wp-content overrides for {{ vhost }}
  find:
    paths: "{{ wh_root }}/sites/{{ vhost }}/wp-content"
    file_type: directory
  register: wp_content_items_find

- debug: msg="Adding site={{ vhost }} with DBpw={{ vhost_db_pass }} and {{ wp_content_items_find | map(attribute='path', default=None) |list }} overrides"

- name: WP docker-compose
  template:
    #src: docker-compose.wp.yml.j2
    src: docker-compose.php-wp.yml.j2
    dest: "{{ wh_root }}/conf/docker-compose.wp-{{ vhost }}.yml"
  register: compose_wp

# Perhaps use "mysql -f" ?
- name: Import DB
  shell: |
    mysql='docker-compose -p wh -f docker-compose.db.yml exec -T db mysql -p{{ wh_MYSQL_ROOT_PASSWORD }}'
    sql={{ wh_root }}/sites/{{ vhost }}/sql
    cd {{ wh_root }}/conf
    echo "CREATE DATABASE \`{{ vhost }}\` CHARSET=utf8;" |
    $mysql
    if [ ! -e $sql/db-imported.sql.gz -o -n "{{ 'init' if wh_init }}" ]; then
    {
    echo "USE \`{{ vhost }}\`;"
    zcat -f $sql/db-init.sql.gz
    } |
    $mysql &&
    mv $sql/db-init.sql.gz $sql/db-imported.sql.gz &&
    touch $sql/db-imported.sql.gz
    fi
    {
    echo "GRANT ALL PRIVILEGES ON \`{{ vhost }}\`.* "
    echo "TO '{{ vhost }}'@'%' IDENTIFIED BY '{{ vhost_db_pass }}';"
    echo "FLUSH PRIVILEGES;"
    } |
    $mysql
  when: compose_wp is changed or wh_init
  register: import_db
  retries: 2  # First import may fail while DB is still initialyzing
  delay: 15

- debug: var=import_db

- name: Disable db-init dump which was just imported
  command: >
    mv
    {{ wh_root }}/sites/{{ vhost }}/sql/db-init.sql.gz
    {{ wh_root }}/sites/{{ vhost }}/sql/db-imported.sql.gz
    && touch
    {{ wh_root }}/sites/{{ vhost }}/sql/db-imported.sql.gz
  args:
    creates: "{{ wh_root }}/sites/{{ vhost }}/sql/db-imported.sql.gz"
    #removes: "{{ wh_root }}/sites/{{ vhost }}/sql/db-init.sql.gz"
  when: compose_wp is changed
  tags: never  # Buggy and not needed after prev. task has been redone

- name: docker-compose up WordPress
  shell: >
    cd {{ wh_root }}/conf &&
    docker-compose
    -f docker-compose.db.yml
    -f docker-compose.wp-{{ vhost }}.yml
    -p wh
    up -d --no-color
  register: output

- debug: var=output
