---

#- import_tasks: install.yml

- import_tasks: conf.yml

- name: Upload sites files
  synchronize:
    src: "{{ wh_src }}/"
    dest: "{{ wh_root }}/sites/"
    #rsync_opts: "-uAHX"
    rsync_opts: "-rltAHX"  # Removes new edits on receiver!

- import_tasks: db-docker.yml

- import_tasks: add-sites.yml

#- import_role: name=fail2ban

...
