---

#- import_tasks: install.yml

- import_tasks: conf.yml

- name: List sites to be added
  find:
    paths: "{{ wh_src }}"
    file_type: directory
  delegate_to: 127.0.0.1
  register: sites
- debug: var=sites.files

- import_tasks: upload-files.yml

- import_tasks: db-docker.yml

- import_tasks: add-sites.yml

#- import_role: name=fail2ban

...
